// <auto-generated />
using System;
using GPMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GPMS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260408151431_AddIsAdminToEmployee")]
    partial class AddIsAdminToEmployee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GPMS.Models.Assignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("assignment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<DateOnly>("AssignedDate")
                        .HasColumnType("date")
                        .HasColumnName("assigned_date");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<int?>("ModuleId")
                        .HasColumnType("int")
                        .HasColumnName("module_id");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.Property<int?>("TaskId")
                        .HasColumnType("int")
                        .HasColumnName("task_id");

                    b.HasKey("AssignmentId");

                    b.HasIndex("ModuleId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("RoleId");

                    b.HasIndex("TaskId");

                    b.HasIndex("EmployeeId", "ProjectId", "ModuleId", "TaskId")
                        .IsUnique()
                        .HasFilter("[project_id] IS NOT NULL AND [module_id] IS NOT NULL AND [task_id] IS NOT NULL");

                    b.ToTable("Assignment");
                });

            modelBuilder.Entity("GPMS.Models.Designation", b =>
                {
                    b.Property<int>("DesignationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("designation_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DesignationId"));

                    b.Property<string>("DesignationDescription")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("designation_description");

                    b.Property<string>("DesignationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("designation_name");

                    b.HasKey("DesignationId");

                    b.HasIndex(new[] { "DesignationName" }, "UQ__Designat__108F431B97E69E20")
                        .IsUnique();

                    b.ToTable("Designation");
                });

            modelBuilder.Entity("GPMS.Models.Document", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("document_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentId"));

                    b.Property<int?>("AssignmentId")
                        .HasColumnType("int")
                        .HasColumnName("assignment_id");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("document_name");

                    b.HasKey("DocumentId");

                    b.HasIndex("AssignmentId");

                    b.ToTable("Document");
                });

            modelBuilder.Entity("GPMS.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<int?>("DesignationId")
                        .HasColumnType("int")
                        .HasColumnName("designation_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("employee_name");

                    b.Property<string>("Epassword")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("epassword");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("SystemRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("system_role");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DesignationId");

                    b.HasIndex(new[] { "Email" }, "UQ__Employee__AB6E61640D4E57BA")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "UQ__Employee__F3DBC572E1224198")
                        .IsUnique()
                        .HasFilter("[username] IS NOT NULL");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("GPMS.Models.Module", b =>
                {
                    b.Property<int>("ModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("module_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModuleId"));

                    b.Property<string>("Details")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("details");

                    b.Property<DateOnly?>("ModuleEndDate")
                        .HasColumnType("date")
                        .HasColumnName("module_end_date");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("module_name");

                    b.Property<DateOnly?>("ModuleStartDate")
                        .HasColumnType("date")
                        .HasColumnName("module_start_date");

                    b.Property<string>("ModuleStatus")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("module_status");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    b.HasKey("ModuleId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Module");
                });

            modelBuilder.Entity("GPMS.Models.Permission", b =>
                {
                    b.Property<int>("PermsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("perms_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermsId"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("description");

                    b.Property<string>("PermsName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("perms_name");

                    b.HasKey("PermsId");

                    b.HasIndex(new[] { "PermsName" }, "UQ__Permissi__B8100928EC646E2C")
                        .IsUnique();

                    b.ToTable("Permission");
                });

            modelBuilder.Entity("GPMS.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("project_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<string>("ProjectDetails")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("project_details");

                    b.Property<DateOnly?>("ProjectEndDate")
                        .HasColumnType("date")
                        .HasColumnName("project_end_date");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("project_name");

                    b.Property<DateOnly>("ProjectStartDate")
                        .HasColumnType("date")
                        .HasColumnName("project_start_date");

                    b.Property<string>("ProjectStatus")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("project_status");

                    b.HasKey("ProjectId");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("GPMS.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<int?>("ParentRoleId")
                        .HasColumnType("int")
                        .HasColumnName("parent_role_id");

                    b.Property<string>("RoleDescription")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("role_description");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId");

                    b.HasIndex("ParentRoleId");

                    b.HasIndex(new[] { "RoleName" }, "UQ__Roles__783254B1E5E34E85")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("GPMS.Models.RolePermission", b =>
                {
                    b.Property<int>("RolePermId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_perm_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolePermId"));

                    b.Property<int>("PermissionId")
                        .HasColumnType("int")
                        .HasColumnName("permission_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("RolePermId");

                    b.HasIndex("PermissionId");

                    b.HasIndex(new[] { "RoleId", "PermissionId" }, "UQ_Role_Permission")
                        .IsUnique();

                    b.ToTable("RolePermission");
                });

            modelBuilder.Entity("GPMS.Models.Task", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("task_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<int>("ModuleId")
                        .HasColumnType("int")
                        .HasColumnName("module_id");

                    b.Property<string>("TaskDescription")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("task_description");

                    b.Property<DateOnly?>("TaskEndDate")
                        .HasColumnType("date")
                        .HasColumnName("task_end_date");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("task_name");

                    b.Property<DateOnly?>("TaskStartDate")
                        .HasColumnType("date")
                        .HasColumnName("task_start_date");

                    b.Property<string>("TaskStatus")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("task_status");

                    b.HasKey("TaskId");

                    b.HasIndex("ModuleId");

                    b.ToTable("Task");
                });

            modelBuilder.Entity("GPMS.Models.Assignment", b =>
                {
                    b.HasOne("GPMS.Models.Employee", "Employee")
                        .WithMany("Assignments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GPMS.Models.Module", "Module")
                        .WithMany("Assignments")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GPMS.Models.Project", "Project")
                        .WithMany("Assignments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("GPMS.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GPMS.Models.Task", "Task")
                        .WithMany("Assignments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Employee");

                    b.Navigation("Module");

                    b.Navigation("Project");

                    b.Navigation("Role");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("GPMS.Models.Document", b =>
                {
                    b.HasOne("GPMS.Models.Assignment", "Assignment")
                        .WithMany("Documents")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("GPMS.Models.Employee", b =>
                {
                    b.HasOne("GPMS.Models.Designation", "Designation")
                        .WithMany("Employees")
                        .HasForeignKey("DesignationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Designation");
                });

            modelBuilder.Entity("GPMS.Models.Module", b =>
                {
                    b.HasOne("GPMS.Models.Project", "Project")
                        .WithMany("Modules")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("GPMS.Models.Role", b =>
                {
                    b.HasOne("GPMS.Models.Role", "ParentRole")
                        .WithMany("InverseParentRole")
                        .HasForeignKey("ParentRoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentRole");
                });

            modelBuilder.Entity("GPMS.Models.RolePermission", b =>
                {
                    b.HasOne("GPMS.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GPMS.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("GPMS.Models.Task", b =>
                {
                    b.HasOne("GPMS.Models.Module", "Module")
                        .WithMany("Tasks")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("GPMS.Models.Assignment", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("GPMS.Models.Designation", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("GPMS.Models.Employee", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("GPMS.Models.Module", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("GPMS.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("GPMS.Models.Project", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Modules");
                });

            modelBuilder.Entity("GPMS.Models.Role", b =>
                {
                    b.Navigation("InverseParentRole");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("GPMS.Models.Task", b =>
                {
                    b.Navigation("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
